### User Classification

#### Importing Required Libraries

In [35]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

#### Reading Data

In [33]:
articles = pd.read_csv("data/news_articles.csv")

In [16]:
df = pd.read_csv("data/train_users.csv")

In [17]:
df.head()

,user_id,age,income,clicks,purchase_amount,session_duration,content_variety,engagement_score,num_transactions,avg_monthly_spend,...,screen_brightness,battery_percentage,cart_abandonment_count,browser_version,background_app_count,session_inactivity_duration,network_jitter,region_code,subscriber,label
0,U7392,NaN,23053,10,500.00,17.34,0.36661,37.29781,3,187.44,...,4.0,2.0,8,3.17.97,10,22.75,8.0,Z999,False,user_3
1,U2702,56.0,20239,11,913.33,22.22,0.61370,59.36342,5,145.15,...,4.5,63.0,5,1.57.10,8,1.75,4.0,U428,True,user_2
2,U2461,NaN,13907,9,1252.62,41.57,0.80368,76.78706,7,282.03,...,1.3,22.0,2,2.16.94,12,29.33,18.0,Z999,True,user_3
3,U7475,NaN,26615,12,500.00,30.17,0.26499,30.19441,10,195.35,...,4.2,77.0,9,9.90.20,4,21.61,22.0,X123,False,user_3
4,U6040,32.0,27958,13,500.00,65.27,0.36385,37.12153,5,439.68,...,4.6,30.0,9,1.99.38,7,7.58,52.0,S043,False,user_1

In [18]:
X = df.drop(columns=['label', 'user_id'])
y = df['label']

#### Preprocessing

In [19]:
X['subscriber'] = X['subscriber'].astype(int)

In [20]:
imputer = SimpleImputer(strategy='median')
X['age'] = imputer.fit_transform(X[['age']])

In [21]:
X = pd.get_dummies(
    X,
    columns=['browser_version', 'region_code'],
    drop_first=True
)

In [22]:
X.head()

,age,income,clicks,purchase_amount,session_duration,content_variety,engagement_score,num_transactions,avg_monthly_spend,avg_cart_value,...,region_code_Z779,region_code_Z795,region_code_Z797,region_code_Z852,region_code_Z873,region_code_Z894,region_code_Z913,region_code_Z925,region_code_Z985,region_code_Z999
0,39.0,23053,10,500.00,17.34,0.36661,37.29781,3,187.44,119.61,...,False,False,False,False,False,False,False,False,False,True
1,56.0,20239,11,913.33,22.22,0.61370,59.36342,5,145.15,189.06,...,False,False,False,False,False,False,False,False,False,False
2,39.0,13907,9,1252.62,41.57,0.80368,76.78706,7,282.03,161.75,...,False,False,False,False,False,False,False,False,False,True
3,39.0,26615,12,500.00,30.17,0.26499,30.19441,10,195.35,23.91,...,False,False,False,False,False,False,False,False,False,False
4,32.0,27958,13,500.00,65.27,0.36385,37.12153,5,439.68,57.68,...,False,False,False,False,False,False,False,False,False,False

In [25]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

#### Train Test Split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

#### Standardization

In [27]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#### Model Fitting

In [29]:
clf_2 = LogisticRegression(
    penalty='l1',
    solver='saga',
    C=0.5,
    max_iter=1000,
    multi_class='multinomial'
)
clf_2.fit(X_train_scaled, y_train)

e:\chrome download\python\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(C=0.5, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

#### Prediction

In [30]:
y_pred = clf_2.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.925
              precision    recall  f1-score   support

           0       0.91      0.88      0.89       142
           1       0.99      0.91      0.95       142
           2       0.88      1.00      0.94       116

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.93      0.93      0.92       400